### PR TITLE
Add Support for Hub2000

### PR DESCRIPTION
**Pull request by ricariel**
Tried to add support for the new hub2000 with these tools.

### CODE REVIEW

**Comment by ricariel** [comment]
Closes #10

**Comment by sstidl** [comment]
Tested your changes. 
You need to patch 2 Lines:
```
diff --git a/src/solarflow-bt-manager.py b/src/solarflow-bt-manager.py
index 3c88e20..f2bdead 100644
--- a/src/solarflow-bt-manager.py
+++ b/src/solarflow-bt-manager.py
@@ -96,7 +96,7 @@ async def set_IoT_Url(client,broker,port,ssid,deviceid):


 def handle_rx(BleakGATTCharacteristic, data: bytearray):
-    global mq_client
+    global mq_client, SF_PRODUCT_ID, SF_DEVICE_ID
     payload = json.loads(data.decode("utf8"))
     log.info(payload)

@@ -113,7 +113,7 @@ def handle_rx(BleakGATTCharacteristic, data: bytearray):
                 mq_client.publish(f'solarflow-hub/telemetry/{prop}',val)

             # also report whole state to mqtt (nothing coming from cloud now :-)
-            mq_client.publish("{SF_PRODUCT_ID}/{deviceid}/state",json.dumps(payload["properties"]))
+            mq_client.publish(f"{SF_PRODUCT_ID}/{SF_DEVICE_ID}/state",json.dumps(payload["properties"]))

         if "packData" in payload:                                                                                                 packdata = payload["packData"]                                                                           @@ -135,6 +135,7 @@ async def run(broker=None, port=None, info_only: bool = False, connect: bool = F
     else:
       product_class = "zenh"                                                                                         
+    log.info("scan for: " + str(product_class))
     device = await BleakScanner.find_device_by_filter(                                                                                lambda d, ad: d.name and d.name.lower().startswith(product_class)
             )                                                                                                        
```

**Comment by ricariel** [comment]
You're right. Fixed that.

**Comment by ricariel** [comment]
> I tried your patched version. Which value should I set SF_PRODUCT_ID to? I have the HUB2000 too

SF_PRODUCT_ID='A8yh63'

**Comment by sstidl** [comment]
> > I tried your patched version. Which value should I set SF_PRODUCT_ID to? I have the HUB2000 too
> 
> SF_PRODUCT_ID='A8yh63'

where did you find that out?

**Comment by sstidl** [comment]
> > > I tried your patched version. Which value should I set SF_PRODUCT_ID to? I have the HUB2000 too
> > 
> > 
> > SF_PRODUCT_ID='A8yh63'
> 
> how did you find that out?

is this the appKey when call the register-api call described here: https://github.com/Zendure/developer-device-data-report ?

**Comment by ricariel** [comment]
> > > I tried your patched version. Which value should I set SF_PRODUCT_ID to? I have the HUB2000 too
> > 
> > 
> > SF_PRODUCT_ID='A8yh63'
> 
> how did you find that out?

I just used the bt tool. There you can see the traffic.

**Comment by sstidl** [comment]
> > > > I tried your patched version. Which value should I set SF_PRODUCT_ID to? I have the HUB2000 too
> > > 
> > > 
> > > SF_PRODUCT_ID='A8yh63'
> > 
> > 
> > how did you find that out?
> 
> I just used the bt tool. There you can see the traffic.

I think you are referring to the device id. 
I don't find the _productid_ in the output of the tool

**Comment by reinhard-brandstaedter** [comment]
It is part of the MQTT topic the hub is writing to:
/productid/deviceid/…

**Pull request merged**
